[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fire>=0.7.1",
    "flake8>=7.3.0",
    "mypy>=2.3.1",
]

[tool.mypy]
python_version = "3.13"

[[tool.mypy.overrides]]
module = "fire.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "fire"
ignore_missing_imports = true
